# Generated by Django 3.1.1 on 2020-12-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('laptop', models.CharField(max_length=10)),
                ('shift', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('parentname', models.CharField(max_length=100)),
                ('stuname', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
