# Generated by Django 3.1.1 on 2020-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_dbt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbt',
            name='question',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
